정상 흐름과 예외 흐름을 구분하기 어렵기 때문에 예외 처리가 등장하였다.

```java
public void sendMessage(String data) {
    String address = "http://example.com";
    NetworkClientV1 client = new NetworkClientV1(address);
    client.initError(data); // 추가

    String connectResult = client.connect();

    // 결과가 성공이 아니다 -> 오류다.
    if (isError(connectResult)) {
        System.out.println("[네트워크 오류 발생] + 오류 코드 : " + connectResult);
    } else {
        String sendResult = client.send(data);
        if (isError(sendResult)) {
            System.out.println("[네트워크 오류 발생] + 오류 코드 : " + sendResult);
        }
    }

    client.disconnect();
}
```
## 예외 계층

자바에서는 예외 처리를 위해 예외 계층을 제공한다.

애플리케이션 개발에서는 Exception부터 잡고 해결하면 된다.

## 예외 던지기와 잡기

- throw : 예외 던지기 (하위 계층 예외도 모두 던짐)
- catch : 예외 잡기 (하위 계층 예외도 모두 잡음)

## 체크 예외

- Exception과 그 하위 예외는 모두 컴파일러가 체크하는 예외이다. (RuntimeException 제외)
- 예외클래스를 만들려면 예외를 상속받는다.
    - Exception을 상속 받은 예외는 체크예외가 된다.
- 체크 예외는 잡아서 직접 처리하거나, 밖으로 던지거나를 개발자가 직접 명시해줘야 하므로 장점이자 단점이 된다. (처리할 예외가 너무 많다)

```java
public class MyCheckedException extends Exception {
 ...   
}
```

### 예외 던지기

- throws : 발생시킨 예외를 메서드 밖으로 던짐
- throw : 예외 발생

```java
public class Client {
    public void call() throws MyCheckedException{
        // 문제 상황
        MyCheckedException ex = new MyCheckedException("ex");
        throw ex;
    }
}
```

### 예외 잡아서 처리하기

```java
public void callCatch() {
    try {
        client.call();
    } catch (MyCheckedException e) {
        // 예외 처리 로직
        System.out.println("예외 처리, message = " + e.getMessage());
    }
    System.out.println("정상 흐름");
}
```

### 예외를 다시 던지기

처리하는 곳 없이 계속 던지기만 하면 에러가 뜨며 종료된다. 단, 스택트레이스와 함께 출력되므로 예외 처리 경로도 알 수 있다.

```java
public void catchThrow() throws MyCheckedException {
    client.call();
}
```

## 언체크 예외

- RuntimeException과 그 하위 예외는 언체크 예외로 처리된다.
- 컴파일러가 예외를 처리하지 않겠다는 의미이다.
- 체크 예외와 기본적으로 동일하지만, throws를 생략할 수 있다는 차이가 있다. 생략할 경우 자동으로 예외를 던진다.
- 언체크 예외는 예외를 잡거나 던지지 않아도 된다. 예외를 잡지 않으면 자동으로 예외를 던진다.
    - 이는 체크 예외와 마찬가지로 장점이자 단점이다. 개발자가 예외를 누락할 수 있다.
- 현대의 개발에서는 체크 예외는 거의 사용하지 않고, 언체크 예외를 사용한다.

## 예외 처리 활용

### 예외 미처리

```java
public void sendMessage(String data) {
    String address = "http://example.com";
    NetworkClientV1 client = new NetworkClientV1(address);
    client.initError(data); // 추가

    client.connect();
    client.send(data);
    client.disconnect();
}
```

### if 예외처리

```java
public class NetworkServiceV1_3 {
    public void sendMessage(String data) {
        String address = "http://example.com";
        NetworkClientV1 client = new NetworkClientV1(address);
        client.initError(data); // 추가

        String connectResult = client.connect();

        // 결과가 성공이 아니다 -> 오류다.
        if (isError(connectResult)) {
            System.out.println("[네트워크 오류 발생] + 오류 코드 : " + connectResult);
        } else {
            String sendResult = client.send(data);
            if (isError(sendResult)) {
                System.out.println("[네트워크 오류 발생] + 오류 코드 : " + sendResult);
            }
        }

        client.disconnect();
    }

    private static boolean isError(String connectResult) {
        return !connectResult.equals("success");
    }
}
```

### 정상흐름 예외흐름 분리

```java
public class NetworkServiceV2_3 {
    public void sendMessage(String data) {
        String address = "http://example.com";
        NetworkClientV2 client = new NetworkClientV2(address);
        client.initError(data); // 추가

        try {
            client.connect();
            client.send(data);
            client.disconnect();
        } catch (NetworkClientExceptionV2 e) {
            System.out.println("[오류] 코드: " + e.getErrorCode() + ", 메시지: " + e.getMessage());
        }
    }
}
```

### disconect() 반드시 호출

단, 이렇게 하면 중간에 catch가 잡지 못할 에러가 발생한다면, disconect()의 실행을 보장하지 못한다. finally를 도입해야 한다.

```java
public class NetworkServiceV2_4 {
    public void sendMessage(String data) {
        String address = "http://example.com";
        NetworkClientV2 client = new NetworkClientV2(address);
        client.initError(data); // 추가

        try {
            client.connect();
            client.send(data);
        } catch (NetworkClientExceptionV2 e) {
            System.out.println("[오류] 코드: " + e.getErrorCode() + ", 메시지: " + e.getMessage());
        }
        client.disconnect();
    }
}
```

### finally 도입

try..catch 에서 잡을 수 없는 에러가 발생해도 반드시 실행한다.

```java
public class NetworkServiceV2_5 {
    public void sendMessage(String data) {
        String address = "http://example.com";
        NetworkClientV2 client = new NetworkClientV2(address);
        client.initError(data); // 추가

        try {
            client.connect();
            client.send(data);
        } catch (NetworkClientExceptionV2 e) {
            System.out.println("[오류] 코드: " + e.getErrorCode() + ", 메시지: " + e.getMessage());
        } finally {
            client.disconnect();
        }
    }
}
```

## 예외 계층

직접 만든 예외도 extends로 계층화가 가능하다. 이렇게 하면 예외 자체를 보고 오류를 이해할 수 있다.

### 예외 계층 활용

현실적으로 모든 예외를 잡을 수 없기 때문에, 가장 중요한 에러는 직접 잡고, 그 이후로는 큰 덩어리로 잡는다.

```java
public class NetworkServiceV3_2 {
    public void sendMessage(String data) {
        String address = "http://example.com";
        NetworkClientV3 client = new NetworkClientV3(address);
        client.initError(data); // 추가

        try {
            client.connect();
            client.send(data);
        } catch (ConnectExceptionV3 e) {
            System.out.println("[연결 오류] 주소: " + e.getAddress() + ", 메시지: " + e.getMessage());
        } catch (NetworkClientExceptionV3 e) {
            System.out.println("[네트워크 오류] 메시지: " + e.getMessage());
        } catch (Exception e) {
            System.out.println("[알 수 없는 오류] 메시지: " + e.getMessage());
        } finally {
            client.disconnect();
        }
    }
}
```

## 실무 예외 처리

### 처리할 수 없는 예외

상대 네트워크에 문제가 생기거나 데이터베이스 서버에 접속할 수 없는 등 처리할 수 없는 예외의 경우 재호출 보다는 고객에게 오류 메시지를 보여준다. 그리고 내부적으로는 로그를 남긴다.

### 체크 예외의 부담

현대의 웹 애플리케이션에서는 체크 예외는 예외가 너무 많아지면서 개발자들이 부담스러워하게 되었다.

## try-with-resource

- 애플리케이션에서 외부 자원을 사용하는 경우 반드시 해제해야 한다 (finally으로 했었다.)
- Java에서는 AutoCloseable 인터페이스를 구현함으로써 자동으로 해제하도록 할 수 있다. (close 메서드를 오버라이딩)
    - 이 메서드는 try가 끝나는 시점에 자동으로 호출된다.
    - try 구문에서는 사용할 자원을 생성한다.
- 리소스 누수 방지 효과
- 코드가 간결해짐
- 스코프가 try 안으로 좁아짐

```java
public class NetworkClientV5 implements AutoCloseable{
    private final String address;
    private boolean connectError;
    private boolean sendError;

    public NetworkClientV5(String address) {
        this.address = address;
    }

    public void connect() {
        if (connectError) {
            throw new ConnectExceptionV4(address, address + " 서버 연결 실패");
        }

        // 연결 성공
        System.out.println(address + " 서버 연결 성공");
    }

    public void send(String data) {
        if (sendError) {
             throw new SendExceptionV4(data, address + " 서버에 데이터 전송 실패: " + data);
        }

        // 전송 성공
        System.out.println(address + " 서버에 데이터 전송: " + data);
    }

    public void disconnect() {
        System.out.println(address + " 서버 연결 해제");
    }

    @Override
    public void close(){
        System.out.println("NetworkClientV5.close");
        disconnect();
    }

    public void initError(String data) {
        if (data.contains("error1")) {
            connectError = true;
        }
        if (data.contains("error2")) {
            sendError = true;
        }
    }
}
```

```java
public class NetworkServiceV5 {
    public void sendMessage(String data) {
        String address = "http://example.com";
        try (NetworkClientV5 client = new NetworkClientV5(address)) {
            client.initError(data); // 추가
            client.connect();
            client.send(data);
        } catch (Exception e) {
            System.out.println("[예외 확인] : " + e.getMessage());
            throw e;
        }
    }
}
```